name: Build and Deploy Grocery Tracker to Azure Container App

on:
  push:
    branches:
      - main  # Change if using a different default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: eadoc/grocery-tracker:latest

     

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
       

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: "grocery-tracker-app"
        resourceGroup: "GroceryTrackerRG"
        imageToDeploy: docker.io/eadoc/grocery-tracker:latest # IMPORTANT: Replace username
     
